// Dados de migração única do adendo "grupos-de-risco" (arquivos
// fundos-grupos-de-risco-backfill.json e cnpj-para-grupo-lookup.json,
// mapeados manualmente a partir da planilha "Fundos Recomendados") — só
// usados por api/init-schema.js pra popular grupo_risco dos 84 fundos já
// cadastrados e semear a tabela cnpj_grupo_risco na primeira vez.

// nome (como está salvo em fundos.nome) -> grupo_risco. 4 fundos sem
// correspondência na planilha ficam em "Sem grupo": AZ Quest Luce II,
// Ibiuna Hedge STH, Subclasse Principal, Subclasse A.
export const BACKFILL_POR_NOME = [
  { nome: "Absolute Hidra CDI Plus P FIC Incentivados Investimento Infra RF", grupo: "RF - PRE ISENTO" },
  { nome: "Absolute Hidra Pré 2 Anos FIF Cotas Incentivados Investimento Infra RF", grupo: "RF - PRE ISENTO" },
  { nome: "Absolute Pace Long Biased FIC FIF Ações", grupo: "AÇÕES BR - LONG BIASED" },
  { nome: "Absolute Vertex FIF Cotas FIM", grupo: "MULTIMERCADO MACRO" },
  { nome: "Access Kapitalo K10 FIF Cotas FIM", grupo: "MULTIMERCADO MACRO" },
  { nome: "Arx Elbrus Fic Incentivado Investimento Financeiro Infra RF RL", grupo: "RF - IPCA+ ISENTO" },
  { nome: "Arx Elbrus Pro Fic Incentivados Investimento Financeiro Infra RF RL", grupo: "RF - IPCA+ ISENTO" },
  { nome: "Arx Fuji Fic FIF RF CP RL", grupo: "RF - CDI BANCÁRIOS" },
  { nome: "AZ Quest Luce II FIC FIF RF CP LP RL", grupo: "Sem grupo" },
  { nome: "BTG Pactual Apolo FIF Cotas FIM", grupo: "RF - HIGH GRADE" },
  { nome: "BTG Pactual Cred Corp Incentivado IPCA FIF Cotas FFI Investimento Infra RF", grupo: "RF - HIGH GRADE" },
  { nome: "BTG Pactual Crédito Corporativo I FIF Cotas FI RF", grupo: "RF - HIGH GRADE" },
  { nome: "BTG Pactual Crédito Corporativo Plus Incentivado CDI FI Investimento Financeiro Infra RF", grupo: "RF - HIGH GRADE" },
  { nome: "Empiricus Selic FIF RF", grupo: "RF - CDI LIQ DIÁRIA" },
  { nome: "Feeder Absolute Vertex FIF Classe FIC Multimercado RL", grupo: "MULTIMERCADO MACRO" },
  { nome: "Genoa Capital Radar Advisory FIF CIC Multimercado RL", grupo: "MULTIMERCADO MACRO" },
  { nome: "Genoa Capital Radar FIF CIC Multimercado RL", grupo: "MULTIMERCADO MACRO" },
  { nome: "Guepardo FIC FIA", grupo: "AÇÕES BR - LONG ONLY" },
  { nome: "Ibiuna Hedge STH FIF Classe FIC Multimercado RL", grupo: "Sem grupo" },
  { nome: "Ibiuna Long Short STLS FIF Classe FIC Multimercado RL", grupo: "AÇÕES BR - LONG/SHORT" },
  { nome: "Icatu Vanguarda Pré Fixado FIF Classe Investimento RF LP RL", grupo: "RF - PRE" },
  { nome: "JGP Debêntures Incentivadas Juros Reais 60 FIF RF Investimento Infra CP RL", grupo: "RF - IPCA+ ISENTO" },
  { nome: "Kapitalo Infra CDI Low Duration FIC Incentivados Infra RF", grupo: "RF - HIGH GRADE ISENTO CDI" },
  { nome: "Kapitalo K10 S FIC FIM", grupo: "MULTIMERCADO MACRO" },
  { nome: "Legacy Capital Credit Advisory CIC CIM CP RL", grupo: "RF - HIGH GRADE" },
  { nome: "Legacy Credit Advisory", grupo: "RF - HIGH GRADE" },
  { nome: "Leto Corporate FIC FIF RF CP LP RL", grupo: "RF - HIGH GRADE" },
  { nome: "Manager Absolute Hidra CDI FIF Investimento Infra CIC Investimento Infra RF RL", grupo: "RF - PRE ISENTO" },
  { nome: "Manager Oaktree Global Credit USD FIF CIC Multimercado CP RL", grupo: "RF - EXTERIOR" },
  { nome: "Mapfre Confianza FIF RF Referenciado DI CP RL", grupo: "RF - CDI BANCÁRIOS" },
  { nome: "Oaktree Global Credit BRL FIC FIM", grupo: "RF - EXTERIOR" },
  { nome: "Oaktree Global Credit BRL FIM", grupo: "RF - EXTERIOR" },
  { nome: "Oaktree Global Credit USD FIC FIM", grupo: "RF - EXTERIOR" },
  { nome: "Occam Liquidez FIC FIF RF Crédito Priv RL", grupo: "RF - CDI HIGH GRADE" },
  { nome: "Organon 60 FIF Cotas FIA", grupo: "AÇÕES BR - SMALL CAPS" },
  { nome: "Organon FIF Cotas FIA", grupo: "AÇÕES BR - SMALL CAPS" },
  { nome: "Panamby Drive IPCA D21 Incentivado Investimento Financeiro Infraestrutura RF", grupo: "RF - HIGH GRADE ISENTO CDI" },
  { nome: "Polo Crédito Corporativo FIC FI RF LP", grupo: "RF - HIGH GRADE" },
  { nome: "Polo FIF RF Investimento Infraestrutura RL", grupo: "RF - HIGH GRADE ISENTO CDI" },
  { nome: "Real Investor FIC FIF Ações RL", grupo: "AÇÕES BR - LONG/SHORT" },
  { nome: "Real Investor FIC FIF Multimercado RL", grupo: "AÇÕES BR - LONG/SHORT" },
  { nome: "Real Investor Imobiliário FIC FIF Multimercado CP RL", grupo: "AÇÕES BR - LONG/SHORT" },
  { nome: "Riza Lotus FIF RF", grupo: "RF - CDI HIGH GRADE" },
  { nome: "Sparta Deb Inc Estrat Incentivados Investimento Financeiro Infra RF RL", grupo: "RF - PRE ISENTO" },
  { nome: "Sparta Deb Inc Inflação FIC Incent Investimento Financeiro Infraest RF RL", grupo: "RF - IPCA+" },
  { nome: "Sparta Debêntures Incentivadas 45 FIC FIF Infraestrutura RF RL", grupo: "RF - IPCA+ ISENTO" },
  { nome: "Sparta Max Advisory FIC FIF RF CP LP RL", grupo: "RF - HIGH GRADE" },
  { nome: "Sparta Max FIC FIF RF CP LP RL", grupo: "RF - HIGH GRADE" },
  { nome: "Sparta Top Inflação FIC FIF RF CP LP RL", grupo: "RF - IPCA+" },
  { nome: "SPX Seahawk FIF CIC RF CP LP RL", grupo: "RF - HIGH GRADE" },
  { nome: "Subclasse Principal", grupo: "Sem grupo" },
  { nome: "SulAmérica Excellence Plus FIF RF CP LP RL", grupo: "RF - CDI BANCÁRIOS" },
  { nome: "SulAmérica Premium Plus FIF RF Ref DI CP RL", grupo: "RF - CDI BANCÁRIOS" },
  { nome: "Tarpon GT 90 FIF Cotas FIA", grupo: "AÇÕES BR - LONG ONLY" },
  { nome: "Tivio Banks RF CP FIF RL", grupo: "RF - CDI BANCÁRIOS" },
  { nome: "V8 Cash Classe FIC Classe Investimento RF RL", grupo: "RF - CDI BANCÁRIOS" },
  { nome: "V8 Cash Platinum CIC Classe Investimento RF CP RL", grupo: "RF - CDI BANCÁRIOS" },
  { nome: "V8 Mercury FIF RF CP LP RL", grupo: "RF - CDI BANCÁRIOS" },
  { nome: "Western Asset US Index 500 FIF Multimercado RL", grupo: "AÇÕES EUA" },
  { nome: "NASD11", grupo: "AÇÕES EUA" },
  { nome: "BITH11", grupo: "CRIPTOMOEDAS" },
  { nome: "IVVB11", grupo: "AÇÕES EUA" },
  { nome: "HASH11", grupo: "CRIPTOMOEDAS" },
  { nome: "SPXR11", grupo: "AÇÕES EUA" },
  { nome: "LVOL11", grupo: "AÇÕES BR - LONG ONLY" },
  { nome: "NTNS11", grupo: "RF - IPCA+" },
  { nome: "IMAB11", grupo: "RF - IPCA+" },
  { nome: "DIVO11", grupo: "AÇÕES BR - LONG ONLY" },
  { nome: "IRFM11", grupo: "RF - PRE" },
  { nome: "PACB11", grupo: "RF - IPCA+" },
  { nome: "ETHE11", grupo: "CRIPTOMOEDAS" },
  { nome: "LFTB11", grupo: "RF - SELIC LIQ DIÁRIA" },
  { nome: "QLBR11", grupo: "AÇÕES BR - LONG ONLY" },
  { nome: "HODL11", grupo: "CRIPTOMOEDAS" },
  { nome: "GOLD11", grupo: "ALTERNATIVOS" },
  { nome: "Classe Única Cotas do Daycoval Classic Estruturado FIC FIDC RL", grupo: "ALTERNATIVOS - FIDCS S/ COME COTAS" },
  { nome: "Classe Única do Solis Capital Antares Advisory FIC FIDC", grupo: "ALTERNATIVOS - FIDCS S/ COME COTAS" },
  { nome: "Classe Única do Solis Capital Antares Light Master FIC FIDC", grupo: "ALTERNATIVOS - FIDCS S/ COME COTAS" },
  { nome: "Classe Única do Valora Vanguard FIC Direitos Creditórios RL", grupo: "ALTERNATIVOS - FIDCS S/ COME COTAS" },
  { nome: "Classe Única FIC do Solis Capital Antares Pioneiro FIC FIDC", grupo: "ALTERNATIVOS - FIDCS S/ COME COTAS" },
  { nome: "KP CP 35 FIDC RL", grupo: "ALTERNATIVOS - FIDCS S/ COME COTAS" },
  { nome: "KP CP FIDC RL", grupo: "ALTERNATIVOS - FIDCS S/ COME COTAS" },
  { nome: "Subclasse A", grupo: "Sem grupo" },
  { nome: "Valora Guardian Advisory FIDC – RL", grupo: "ALTERNATIVOS - FIDCS S/ COME COTAS" },
];

// CNPJ (só dígitos) -> grupo_risco, extraído da planilha original — semeia
// cnpj_grupo_risco na primeira vez (ON CONFLICT DO NOTHING: não sobrescreve
// correção feita por um admin depois, ver api/fundos/[id].js).
export const CNPJ_PARA_GRUPO = {
  "35816893000122": "RF - CDI LIQ DIÁRIA",
  "29562673000117": "RF - CDI LIQ DIÁRIA",
  "51253495000100": "RF - CDI BANCÁRIOS",
  "52286231000107": "RF - CDI BANCÁRIOS",
  "47715703000160": "RF - CDI BANCÁRIOS",
  "10347493000194": "RF - CDI BANCÁRIOS",
  "42774627000140": "RF - CDI BANCÁRIOS",
  "55763285000104": "RF - CDI BANCÁRIOS",
  "58398452000153": "RF - CDI BANCÁRIOS",
  "36498670000127": "RF - CDI HIGH GRADE",
  "46098897000139": "RF - CDI HIGH GRADE",
  "68238144000114": "RF - HIGH GRADE ISENTO CDI",
  "64932133000189": "RF - HIGH GRADE ISENTO CDI",
  "62438200000188": "RF - HIGH GRADE ISENTO CDI",
  "63953556000112": "RF - HIGH GRADE ISENTO CDI",
  "56659299000145": "RF - HIGH GRADE",
  "39511032000197": "RF - HIGH GRADE",
  "14171644000157": "RF - HIGH GRADE",
  "57661754000100": "RF - HIGH GRADE",
  "14188162000100": "RF - HIGH GRADE",
  "35505971000178": "RF - HIGH GRADE",
  "26773148000152": "RF - HIGH GRADE",
  "45064129000100": "RF - HIGH GRADE",
  "50038992000114": "RF - PRE ISENTO",
  "63904226000137": "RF - PRE ISENTO",
  "32880642000119": "RF - PRE",
  "19418031000195": "RF - PRE",
  "37368116000198": "RF - IPCA+ ISENTO",
  "30910199000156": "RF - IPCA+ ISENTO",
  "39959025000152": "RF - IPCA+ ISENTO",
  "54237051000160": "RF - IPCA+ ISENTO",
  "38026926000129": "RF - IPCA+",
  "50642881000112": "RF - IPCA+",
  "31024153000100": "RF - IPCA+",
  "44702829000101": "RF - IPCA+",
  "40660810000199": "RF - EXTERIOR",
  "29853005000149": "RF - EXTERIOR",
  "38221267000181": "ALTERNATIVOS - FIDCS S/ COME COTAS",
  "28903657000188": "ALTERNATIVOS - FIDCS S/ COME COTAS",
  "34780531000166": "ALTERNATIVOS - FIDCS S/ COME COTAS",
  "34583819000140": "ALTERNATIVOS - FIDCS S/ COME COTAS",
  "55318040000178": "ALTERNATIVOS - FIDCS S/ COME COTAS",
  "38058318000104": "ALTERNATIVOS - FIDCS S/ COME COTAS",
  "59657690000107": "ALTERNATIVOS - FIDCS S/ COME COTAS",
  "60571986000181": "ALTERNATIVOS - FIDCS S/ COME COTAS",
  "21470989000177": "MULTIMERCADO MACRO",
  "35828684000107": "MULTIMERCADO MACRO",
  "43984537000146": "MULTIMERCADO MACRO",
  "28911549000157": "AÇÕES BR - LONG/SHORT",
  "18391138000124": "AÇÕES BR - LONG/SHORT",
  "14438229000117": "AÇÕES BR - LONG ONLY",
  "10500884000105": "AÇÕES BR - LONG ONLY",
  "42922205000174": "AÇÕES BR - LONG ONLY",
  "06035405000141": "AÇÕES BR - LONG ONLY",
  "32073525000143": "AÇÕES BR - LONG BIASED",
  "17400251000166": "AÇÕES BR - SMALL CAPS",
  "52242659000158": "AÇÕES BR - SMALL CAPS",
  "17453850000148": "AÇÕES EUA",
  "58022660000153": "AÇÕES EUA",
  "19909560000191": "AÇÕES EUA",
  "35578672000163": "AÇÕES EUA",
  "41256573000168": "CRIPTOMOEDAS",
  "41907631000176": "CRIPTOMOEDAS",
  "38314708000190": "CRIPTOMOEDAS",
};
